CREATE SEQUENCE seq_centro_vacinacao
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE seq_vacinas
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE seq_cidadaos
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE seq_agendamentos
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE SEQUENCE seq_registros_aplicacoes
START WITH 1
INCREMENT BY 1
NOCACHE;
